FROM {{ os_version }}

LABEL maintainer="O1.IO"
{% if system_dependencies|length > 0 %}

RUN {{ package_manager }} update -y && \
    {{ package_manager }} install -y {{ system_dependencies|join(' ') }}
{% endif %}

ENV GETH_HOME=/opt/geth
WORKDIR $GETH_HOME
RUN curl -L {{ archive_url }} | tar xzf - --strip-components=1 -C $GETH_HOME

RUN mkdir /entrypoint.d
COPY entrypoints/setup-config.sh /entrypoint.d

COPY scripts/entrypoint.sh /entrypoint.sh
COPY scripts/start-geth.sh /usr/bin/start-geth.sh
RUN chmod +x /entrypoint.sh /usr/bin/start-geth.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["start-geth.sh"]
