version: "3"

networks:
  ethereum:

services:
  geth:
    image: ${image:-0labs/geth:latest}
    container_name: geth
    command:
      - "geth"
      - "--${chain:-rinkeby}"
      - "--log.${log_opt:-json}"
      - "--http"
      - "--metrics"
    environment:
      GETH_CONFIG_DIR: ${GETH_CONFIG_DIR:-/etc/geth}
    env_file:
      - ${env_vars:-.env}
    ports:
      - ${p2p_port:-30303}:30303/tcp
      - ${rpc_port:-8545}:8545
      - ${ws_port:-8546}:8546
      - ${metrics_port:-6060}:6060
    volumes:
      - "${host_data_dir:-/var/tmp/geth}:${data_dir:-/root/.ethereum}"
    networks:
      - ethereum
    restart: ${restart_policy:-unless-stopped}

  geth-exporter:
    image: ${exporter_image:-hunterlong/gethexporter:latest}
    container_name: geth-exporter
    environment:
      GETH: "${exporter_rpc_addr:-http://geth:8545}"
    ports:
      - ${exporter_port:-10090}:9090
    networks:
      - ethereum
    restart: ${restart_policy:-unless-stopped}
