version: "3"

networks:
  ethereum:
  monitoring:

services:
  geth:
    image: ${image:-0labs/geth:latest}
    container_name: geth
    command:
      - "geth"
      - "--${chain:-rinkeby}"
      - "--log.debug"
      - "--config=${GETH_CONFIG_DIR:-/etc/geth}/config.toml"
      - "--http"
      - "--metrics"
      - "--metrics.addr=${metrics_addr:-0.0.0.0}"
      - "--nat=extip:${external_addr:-127.0.0.1}"
    environment:
      GETH_CONFIG_DIR: ${GETH_CONFIG_DIR:-/etc/geth}
    env_file:
      - ${env_vars:-.env}
    ports:
      - ${p2p_port:-30303}:30303/tcp
      - ${rpc_port:-8545}:8545
      - ${metrics_port:-6060}:6060
    volumes:
      - "${host_data_dir:-/operations/ethereum/geth/data}:${data_dir:-/root/.ethereum}"
    networks:
      - ethereum
      - monitoring
    restart: ${restart_policy:-unless-stopped}

  geth-exporter:
    image: ${exporter_image:-hunterlong/gethexporter:latest}
    container_name: geth-exporter
    environment:
      GETH: "${exporter_rpc_addr:-http://geth:8545}"
    ports:
      - ${exporter_port:-10090}:9090
    networks:
      - ethereum
      - monitoring
    restart: ${restart_policy:-unless-stopped}
