#!/bin/bash

# Print all commands executed if DEBUG mode enabled
[ -n "${DEBUG:-""}" ] && set -x

if [[ -n ${GENESIS_INIT_PATH} ]]; then
    curl -o /tmp/genesis.json ${GENESIS_INIT_PATH}
    
    # identify client configured datadir if set
    d=$(env | grep "CONFIG-Node-DataDir" | cut -d'=' -f2)
    geth init /tmp/genesis.json --datadir "${d:-/root/.ethereum}"
fi
