#!/bin/bash

# Print all commands executed if DEBUG mode enabled
[ -n "${DEBUG:-""}" ] && set -x

keystore_dir="${KEYSTORE:-/root/.ethereum/keystore}"
backup_path="${BACKUP_PATH:-/tmp/backup/wallet-backup.zip}"
backup_interval="${BACKUP_INTERVAL:-0 * * * *}" # @hourly by default
backup_cmd="geth-helper account backup-keystore $BACKUP_PASSWORD --keystore-dir $keystore_dir --backup-path $backup_path"

mkdir -p $(dirname ${backup_path})
if [[ -n $BACKUP_KEYSTORE ]]; then
    service cron start
	echo "${backup_interval} ${backup_cmd}" > /tmp/geth-cron
	crontab /tmp/geth-cron && rm /tmp/geth-cron
fi
