#!/bin/bash

# Print all commands executed if DEBUG mode enabled
[ -n "${DEBUG:-""}" ] && set -x

config_dir="${GETH_CONFIG_DIR:-/root/.ethereum/geth}"
config_path="${config_dir}/config.toml"

mkdir -p $config_dir

# customize config based on "CONFIG_<section>_<setting>" set environment variables
geth-helper config customize --config-path $config_path

# remove surrounding quotes from ALL section names if necessary
sed -i 's/\[\"/\[/g' $config_path
sed -i 's/\"\]/\]/g' $config_path
